name: snekkyd

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: mv cpp/SnekkyD cpp/snekkyd
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-linux
          path: cpp/snekkyd
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: | 
          cd cpp
          ren SnekkyD.exe snekkyd.exe
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-win
          path: cpp/snekkyd.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: mv cpp/SnekkyD cpp/snekkyd
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-macos
          path: cpp/snekkyd
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build-js.hxml
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-js
          path: js/snekkyd.js